/*
 * UnembedFrame.java
 *
 * Created on 8 marzo 2008, 17.16
 */
package gui;

import com.sun.org.apache.bcel.internal.generic.IFEQ;
import javax.swing.JOptionPane;
import ssis.ecc.ECC;
import ssis.ecc.combined_H_RS.CombinedHammRS;
import ssis.ecc.hamming.HammingECC;
import ssis.ecc.reedSolomon.RS_ECC;

/**
 *
 * @author  sergio
 */
public class UnembedFrame extends javax.swing.JFrame {

    /** Creates new form UnembedFrame */
    public UnembedFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBoxECC = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldN = new javax.swing.JTextField();
        jTextFieldM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxModulazione = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIterazioni = new javax.swing.JTextField();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPasswordField1.setColumns(10);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPasswordField1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setText("Password:");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Annulla");
        jButton2.setDefaultCapable(false);

        jComboBoxECC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hamming", "Reed-Solomon", "Combinato" }));
        jComboBoxECC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxECCActionPerformed(evt);
            }
        });

        jLabel2.setText("ECC:");

        jLabel3.setText("(N, M):");

        jTextFieldN.setColumns(2);
        jTextFieldN.setText("3");
        jTextFieldN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNActionPerformed(evt);
            }
        });

        jTextFieldM.setColumns(2);
        jTextFieldM.setText("1");
        jTextFieldM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMActionPerformed(evt);
            }
        });

        jLabel4.setText(",");

        jLabel5.setText("Modulazione:");

        jComboBoxModulazione.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Piecewise", "Sign Detector" }));
        jComboBoxModulazione.setEnabled(false);

        jLabel6.setText("x");

        jTextFieldIterazioni.setColumns(2);
        jTextFieldIterazioni.setText("3");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel2)
                    .add(jLabel1)
                    .add(jLabel3)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jComboBoxECC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPasswordField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(jTextFieldN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextFieldM, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jComboBoxModulazione, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextFieldIterazioni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jPasswordField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxECC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(jLabel6)
                    .add(jTextFieldIterazioni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextFieldN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(jTextFieldM, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jComboBoxModulazione, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jPasswordField1.getPassword().length <= 0) {
            JOptionPane.showConfirmDialog(rootPane, "Devi iserire una password");
        } else {
            Controller controller = Controller.getInstance();
            int n = -1;
            int m = -1;
            int iter = -1;
            int tipoECC = jComboBoxECC.getSelectedIndex();
            if (tipoECC == 0)//hamming
            {
                n = Integer.parseInt(jTextFieldN.getText());
                m = Integer.parseInt(jTextFieldM.getText());
                iter = Integer.parseInt(jTextFieldIterazioni.getText());
                tipoECC = ECC.ECC_HAMMING;
            } else if (tipoECC == 1)//reed-solomon
            {
                n = Integer.parseInt(jTextFieldN.getText());
                m = Integer.parseInt(jTextFieldM.getText());
                iter = Integer.parseInt(jTextFieldIterazioni.getText());
                tipoECC = ECC.ECC_REED_SOLOMON;
            } else if (tipoECC == 2)//reed-solomon
            {
                tipoECC = ECC.ECC_COMBINED;
            }

            this.dispose();


            controller.trovaMsgSSIS(String.valueOf(jPasswordField1.getPassword()),
                    n,
                    m,
                    iter,
                    tipoECC);



        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxECCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxECCActionPerformed

        if (jComboBoxECC.getSelectedIndex() == 0) {//Hamming
            jTextFieldN.setText("" + HammingECC.STANDARD_N);
            jTextFieldM.setText("" + HammingECC.STANDARD_M);
            jTextFieldIterazioni.setText("" + HammingECC.STANDARD_ITER);
        } else if (jComboBoxECC.getSelectedIndex() == 1) {//Reed-Solomon
            jTextFieldN.setText("" + RS_ECC.STANDARD_N);
            jTextFieldM.setText("" + RS_ECC.STANDARD_M);
            jTextFieldIterazioni.setText("" + RS_ECC.STANDARD_ITER);
        } else if (jComboBoxECC.getSelectedIndex() == 2) {//combinato
            jTextFieldN.setEnabled(false);
            jTextFieldM.setEnabled(false);
            jTextFieldIterazioni.setEnabled(false);
        }
        
}//GEN-LAST:event_jComboBoxECCActionPerformed

    private void jTextFieldNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldNActionPerformed

    private void jPasswordField1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPasswordField1AncestorMoved
    // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1AncestorMoved

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        this.jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextFieldMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UnembedFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBoxECC;
    private javax.swing.JComboBox jComboBoxModulazione;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldIterazioni;
    private javax.swing.JTextField jTextFieldM;
    private javax.swing.JTextField jTextFieldN;
    // End of variables declaration//GEN-END:variables
}
